"""n8n webhook endpoints — orchestrate the research cycle from n8n.

n8n calls these endpoints instead of the APScheduler loop.
LOOP_STATE is updated at each step so the existing UI works unchanged.
"""

from __future__ import annotations

import json
import logging
import random
import asyncio
from datetime import datetime

from fastapi import APIRouter, Request, Body
from fastapi.responses import JSONResponse

from app.database import get_db
from app.services.autoresearch_service import AutoresearchService, RESCORE_STATE

logger = logging.getLogger("okoone.n8n")
router = APIRouter(prefix="/api/n8n", tags=["n8n"])

research = AutoresearchService()


def _loop(request: Request) -> dict:
    return getattr(request.app.state, "loop_state", {})


def _step(request: Request, status: str, step: str):
    ls = _loop(request)
    ls["status"] = status
    ls["current_step"] = step
    logger.info("n8n step: [%s] %s", status, step)


# --- Cycle lifecycle ---

@router.post("/cycle/start")
async def cycle_start(request: Request):
    """Mark cycle as running. Returns cycle context (program, weights, etc)."""
    ls = _loop(request)
    ls["active"] = True
    _step(request, "searching", "n8n: cycle demarre...")

    async with get_db() as db:
        cur = await db.execute(
            "SELECT version, content FROM prospect_program WHERE status = 'active' ORDER BY version DESC LIMIT 1"
        )
        prog = await cur.fetchone()

        cur2 = await db.execute("SELECT * FROM acquaintances ORDER BY created_at DESC")
        acqs = [dict(r) for r in await cur2.fetchall()]

        cur3 = await db.execute("SELECT criteria_json FROM scoring_weights WHERE is_active = 1 LIMIT 1")
        w = await cur3.fetchone()

        cur4 = await db.execute("""
            SELECT COUNT(*) as total,
                   SUM(CASE WHEN hr.reviewer_verdict = 'approve' THEN 1 ELSE 0 END) as approved,
                   SUM(CASE WHEN hr.reviewer_verdict = 'reject' THEN 1 ELSE 0 END) as rejected
            FROM prospects p LEFT JOIN human_reviews hr ON hr.prospect_id = p.id
            WHERE p.created_at > datetime('now', '-7 days')
        """)
        stats = dict(await cur4.fetchone())

        cur5 = await db.execute(
            "SELECT DISTINCT keywords FROM search_queries ORDER BY created_at DESC LIMIT 100"
        )
        past = [r[0] for r in await cur5.fetchall()]

        metrics_history = await research._load_metrics_history(db, limit=5)
        query_perf = await research._load_query_performance(db, limit=15)

    return {
        "program_version": prog[0] if prog else 0,
        "program_content": prog[1] if prog else "",
        "acquaintances": acqs,
        "weights": json.loads(w[0]) if w else {},
        "stats_7d": stats,
        "past_queries": past,
        "metrics_history": metrics_history,
        "query_performance": query_perf,
    }


@router.post("/cycle/step")
async def cycle_step(request: Request, status: str = Body(""), step: str = Body("")):
    """Update LOOP_STATE from n8n (progress reporting)."""
    _step(request, status, step)
    return {"ok": True}


# --- Query storage (queries generated by n8n Claude node) ---

@router.post("/queries")
async def store_queries(request: Request, queries: list[dict] = Body(...)):
    """Store generated queries and return them with IDs."""
    _step(request, "searching", f"n8n: {len(queries)} queries generees")

    async with get_db() as db:
        stored = []
        for q in queries[:10]:
            cur = await db.execute(
                "INSERT INTO search_queries (keywords, location) VALUES (?, ?)",
                (q.get("keywords", ""), q.get("location")),
            )
            stored.append({**q, "id": cur.lastrowid})
        await db.commit()

    return {"queries": stored}


# --- LinkedIn scraping (stays in Python, browser needed) ---

@router.post("/scrape")
async def scrape(request: Request, queries: list[dict] = Body(...)):
    """Execute LinkedIn scraping. Browser stays in Python."""
    from app.repositories.prospect_repo import ProspectRepository
    from app.scraper.rate_limiter import DailyLimitReached
    from app.scheduler.jobs import _auto_relogin

    scraper = request.app.state.scraper
    if not scraper:
        return JSONResponse({"error": "Scraper not initialized"}, 500)

    if not scraper._browser:
        _step(request, "searching", "n8n: demarrage navigateur...")
        await scraper.start()

    session_valid = await scraper.is_session_valid()
    if not session_valid:
        _step(request, "searching", "n8n: session expiree, tentative reconnexion...")
        session_valid = await _auto_relogin(scraper)
        if not session_valid:
            return JSONResponse({"error": "LinkedIn session expired", "session_valid": False}, 200)

    total_found = 0
    total_new = 0
    rate_limited = False

    async with get_db() as db:
        repo = ProspectRepository(db)

        for i, q in enumerate(queries[:10]):
            kw = q["keywords"]
            loc = q.get("location")
            search_id = q.get("id")
            _step(request, "searching", f"n8n: recherche {i+1}/{len(queries[:10])}: {kw[:40]}...")

            try:
                results = await scraper.search_people(kw, loc)

                if results:
                    for pg in range(2, 51):
                        await asyncio.sleep(random.uniform(2.0, 5.0))
                        try:
                            pg_results = await scraper.search_people(kw, loc, page=pg)
                            if not pg_results:
                                break
                            results.extend(pg_results)
                        except DailyLimitReached:
                            raise
                        except Exception:
                            break

                if not results:
                    simplified = " ".join(kw.split()[:2])
                    if simplified != kw:
                        await asyncio.sleep(random.uniform(2.0, 4.0))
                        results = await scraper.search_people(simplified, loc)

                total_found += len(results)

                for p in results:
                    username = (p.get("profile_username") or "").strip("/").split("/")[-1]
                    if not username or len(username) < 2:
                        continue
                    _, is_new = await repo.upsert_by_username(username, {
                        "full_name": p.get("full_name", ""),
                        "headline": p.get("headline", ""),
                        "location": p.get("location", ""),
                        "linkedin_url": f"https://www.linkedin.com/in/{username}/",
                        "linkedin_username": username,
                        "source_search_id": search_id,
                        "scraped_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                    })
                    if is_new:
                        total_new += 1
                await db.commit()

            except DailyLimitReached:
                rate_limited = True
                break
            except Exception:
                logger.error("Scrape error for '%s':", kw, exc_info=True)

    # Deep screening (fetch full profiles)
    deep_screened = 0
    if session_valid:
        _step(request, "evaluating", "n8n: deep screening des profils...")
        async with get_db() as db:
            repo = ProspectRepository(db)
            cur = await db.execute(
                "SELECT id, linkedin_username FROM prospects "
                "WHERE (experience_json IS NULL OR experience_json = '' OR experience_json = '[]') "
                "AND linkedin_username IS NOT NULL "
                "ORDER BY created_at DESC LIMIT 20"
            )
            shallow = await cur.fetchall()

            for i, sp in enumerate(shallow):
                if i > 0:
                    pause = random.uniform(3, 8)
                    if random.random() < 0.2:
                        pause = random.uniform(15, 30)
                    await asyncio.sleep(pause)

                pid, username = sp[0], sp[1]
                _step(request, "evaluating", f"n8n: deep screen {i+1}/{len(shallow)}: {username}...")
                try:
                    profile = await scraper.get_person_profile(username)
                    if profile:
                        update = {}
                        for k, col in [("full_name", "full_name"), ("headline", "headline"),
                                        ("location", "location"), ("about", "about_text"),
                                        ("current_company", "current_company"), ("current_title", "current_title"),
                                        ("profile_photo_url", "profile_photo_url")]:
                            if profile.get(k):
                                update[col] = profile[k]
                        for k, col in [("experience", "experience_json"), ("education", "education_json"),
                                        ("skills", "skills_json")]:
                            if profile.get(k):
                                update[col] = json.dumps(profile[k])
                        update["screened_at"] = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                        if update:
                            await repo.update(pid, update)
                            deep_screened += 1
                except DailyLimitReached:
                    break
                except Exception:
                    logger.error("Deep screen error for %s:", username, exc_info=True)
            await db.commit()

    return {
        "total_found": total_found,
        "total_new": total_new,
        "deep_screened": deep_screened,
        "rate_limited": rate_limited,
        "session_valid": session_valid,
    }


# --- Algorithmic scoring (no Claude) ---

@router.post("/score")
async def score_prospects(request: Request):
    """Score all unscored prospects (algorithmic, no Claude)."""
    _step(request, "evaluating", "n8n: scoring algorithmique...")

    async with get_db() as db:
        cur = await db.execute("SELECT id FROM prospects WHERE relevance_score = 0 OR relevance_score IS NULL")
        unscored = [r[0] for r in await cur.fetchall()]

        w_cur = await db.execute("SELECT criteria_json FROM scoring_weights WHERE is_active = 1 LIMIT 1")
        w = await w_cur.fetchone()

        scored = 0
        if w and unscored:
            from app.services.scoring_service import ScoringService
            from app.repositories.prospect_repo import ProspectRepository

            scoring = ScoringService()
            repo = ProspectRepository(db)
            weights = json.loads(w[0])

            for pid in unscored:
                prospect = await repo.find_by_id(pid)
                if prospect:
                    score, breakdown = await scoring.score_prospect(prospect, weights)
                    summary = scoring.generate_score_summary(breakdown, weights, prospect)
                    await repo.update(pid, {
                        "relevance_score": score,
                        "score_breakdown": json.dumps(breakdown),
                        "score_summary": summary,
                        "status": "screened",
                    })
                    scored += 1
            await db.commit()

    return {"scored": scored, "total_unscored": len(unscored)}


# --- Prospects for Claude analysis (done by n8n Execute Command) ---

@router.get("/prospects/unanalyzed")
async def unanalyzed_prospects(request: Request, limit: int = 5):
    """Return prospects that need Claude deep analysis."""
    async with get_db() as db:
        cur = await db.execute(
            "SELECT id, full_name, headline, current_company, location, "
            "about_text, experience_json, education_json, skills_json, "
            "relevance_score, score_summary "
            "FROM prospects "
            "WHERE experience_json IS NOT NULL AND experience_json != '' AND experience_json != '[]' "
            "AND (claude_analysis IS NULL OR claude_analysis = '') "
            "ORDER BY relevance_score DESC LIMIT ?",
            (limit,),
        )
        rows = [dict(r) for r in await cur.fetchall()]

        prog_cur = await db.execute(
            "SELECT content FROM prospect_program WHERE status = 'active' ORDER BY version DESC LIMIT 1"
        )
        prog = await prog_cur.fetchone()

        acq_cur = await db.execute("SELECT * FROM acquaintances ORDER BY created_at DESC")
        acqs = [dict(r) for r in await acq_cur.fetchall()]

    return {
        "prospects": rows,
        "program": prog[0] if prog else "",
        "acquaintances": acqs,
    }


@router.post("/prospects/{pid}/analysis")
async def store_analysis(request: Request, pid: int, analysis: dict = Body(...)):
    """Store Claude deep analysis result for a prospect."""
    _step(request, "analyzing", f"n8n: analyse prospect #{pid} stockee")

    async with get_db() as db:
        from app.repositories.prospect_repo import ProspectRepository
        repo = ProspectRepository(db)
        await repo.update(pid, {"claude_analysis": json.dumps(analysis, ensure_ascii=False)})
        await db.commit()

    return {"ok": True}


# --- Web research ---

@router.get("/prospects/unresearched")
async def unresearched_prospects(request: Request, limit: int = 5):
    """Return prospects that need web research enrichment."""
    async with get_db() as db:
        cur = await db.execute(
            "SELECT id, full_name, current_title, headline, current_company, location "
            "FROM prospects "
            "WHERE experience_json IS NOT NULL AND experience_json != '' AND experience_json != '[]' "
            "AND (web_research_json IS NULL OR web_research_json = '') "
            "ORDER BY relevance_score DESC LIMIT ?",
            (limit,),
        )
        rows = [dict(r) for r in await cur.fetchall()]

    return {"prospects": rows}


@router.post("/prospects/{pid}/web-research")
async def store_web_research(request: Request, pid: int, research_data: dict = Body(...)):
    """Store web research result for a prospect."""
    _step(request, "analyzing", f"n8n: web research prospect #{pid} stockee")

    async with get_db() as db:
        from app.repositories.prospect_repo import ProspectRepository
        repo = ProspectRepository(db)
        await repo.update(pid, {"web_research_json": json.dumps(research_data, ensure_ascii=False)})
        await db.commit()

    return {"ok": True}


# --- Strategy improvement ---

@router.post("/strategy/propose")
async def store_proposal(
    request: Request,
    proposed_program: str = Body(""),
    analysis: str = Body(""),
    run_id: int = Body(0),
):
    """Store strategy proposal and auto-accept if configured."""
    from app.config import settings

    _step(request, "proposing", "n8n: proposition de strategie recue")

    async with get_db() as db:
        if run_id:
            await db.execute("""
                UPDATE research_runs SET proposed_program = ?, proposal_reasoning = ? WHERE id = ?
            """, (proposed_program, (analysis or "")[:2000], run_id))
            await db.commit()

        applied_version = None
        if settings.AUTO_ACCEPT_IMPROVEMENTS and proposed_program:
            new_v = await research.apply_program(db, proposed_program, author="claude-auto-n8n")
            applied_version = new_v
            if run_id:
                await db.execute(
                    "UPDATE research_runs SET proposal_status = 'auto-accepted' WHERE id = ?",
                    (run_id,),
                )
                await db.execute(
                    "UPDATE prospect_program SET trigger = 'n8n-auto', change_reason = ? WHERE version = ?",
                    (f"Auto-accepted from n8n run#{run_id}", new_v),
                )
            await db.commit()
            logger.info("n8n KARPATHY KEEP: program v%d accepted", new_v)

    return {"ok": True, "applied_version": applied_version}


# --- Cycle finish ---

@router.post("/cycle/finish")
async def cycle_finish(
    request: Request,
    total_new: int = Body(0),
    total_found: int = Body(0),
    scored: int = Body(0),
    analyzed: int = Body(0),
    web_researched: int = Body(0),
    metrics: dict = Body(None),
):
    """Finalize cycle, record run, update LOOP_STATE."""
    ls = _loop(request)

    async with get_db() as db:
        v_cur = await db.execute(
            "SELECT version FROM prospect_program WHERE status = 'active' ORDER BY version DESC LIMIT 1"
        )
        v = await v_cur.fetchone()

        await db.execute("""
            INSERT INTO research_runs
                (program_version, finished_at, status, prospects_found, prospects_qualified, metric_json)
            VALUES (?, datetime('now'), ?, ?, ?, ?)
        """, (
            v[0] if v else 0,
            "completed" if total_new > 0 else "no_results",
            total_new,
            scored,
            json.dumps(metrics) if metrics else None,
        ))
        await db.commit()

        cur = await db.execute("SELECT last_insert_rowid()")
        run_id = (await cur.fetchone())[0]

    ls["status"] = "sleeping"
    ls["last_run_at"] = datetime.now().strftime("%Y-%m-%d %H:%M")
    ls["cycles_completed"] = ls.get("cycles_completed", 0) + 1
    ls["total_prospects_found"] = ls.get("total_prospects_found", 0) + total_new
    ls["total_qualified"] = ls.get("total_qualified", 0) + scored
    ls["last_error"] = None

    if total_new == 0:
        ls["consecutive_empty_runs"] = ls.get("consecutive_empty_runs", 0) + 1
        ls["current_step"] = f"n8n: cycle termine. 0 nouveaux (#{ls['consecutive_empty_runs']} consecutif)"
    else:
        ls["consecutive_empty_runs"] = 0
        ls["current_step"] = (
            f"n8n: cycle termine. +{total_new} prospects, {scored} scores, "
            f"{analyzed} analyses, {web_researched} recherches web"
        )

    ls["last_run_result"] = {
        "source": "n8n",
        "found": total_found,
        "new": total_new,
        "scored": scored,
        "analyzed": analyzed,
        "web_researched": web_researched,
    }

    return {"ok": True, "run_id": run_id}


# --- Status ---

@router.get("/cycle/status")
async def cycle_status(request: Request):
    """Return current cycle state for monitoring."""
    return _loop(request)
"""Additional n8n batch endpoints — Claude calls stay inside the CRM.

n8n orchestrates the order, the CRM does the actual Claude CLI calls.
Appended to the n8n router.
"""

from app.services.claude_advisor import _call_claude, MODEL_FAST, MODEL_SMART
from app.services.deep_analysis_service import DeepAnalysisService


# --- Batch: generate queries (CRM calls Claude internally) ---

@router.post("/generate-queries")
async def generate_queries(request: Request):
    """Generate search queries using Claude (Sonnet). Returns the queries."""
    _step(request, "searching", "n8n: Claude genere des requetes...")

    async with get_db() as db:
        queries = await research.generate_search_plan(db)

    if not queries:
        return {"queries": [], "message": "Claude n'a genere aucune query"}

    # Store queries
    async with get_db() as db:
        stored = []
        for q in queries[:10]:
            cur = await db.execute(
                "INSERT INTO search_queries (keywords, location) VALUES (?, ?)",
                (q.get("keywords", ""), q.get("location")),
            )
            stored.append({**q, "id": cur.lastrowid})
        await db.commit()

    _step(request, "searching", f"n8n: {len(stored)} queries generees par Claude")
    return {"queries": stored}


# --- Batch: deep analysis (CRM calls Claude internally) ---

@router.post("/analyze-batch")
async def analyze_batch(request: Request, limit: int = Body(5)):
    """Analyze unanalyzed prospects using Claude (Sonnet). CRM does the calls."""
    _step(request, "analyzing", "n8n: analyse Claude en cours...")

    deep_svc = DeepAnalysisService()
    analyzed = 0

    async with get_db() as db:
        _, prog_content = await research._load_program(db)
        acqs = await research._load_acquaintances(db)

        cur = await db.execute(
            "SELECT id FROM prospects "
            "WHERE experience_json IS NOT NULL AND experience_json != '' AND experience_json != '[]' "
            "AND (claude_analysis IS NULL OR claude_analysis = '') "
            "ORDER BY relevance_score DESC LIMIT ?",
            (limit,),
        )
        ids = [r[0] for r in await cur.fetchall()]

        from app.repositories.prospect_repo import ProspectRepository
        repo = ProspectRepository(db)

        for i, pid in enumerate(ids):
            _step(request, "analyzing", f"n8n: analyse Claude {i+1}/{len(ids)}...")
            prospect = await repo.find_by_id(pid)
            if not prospect:
                continue
            try:
                analysis = await deep_svc.analyze_prospect(prospect, prog_content, acqs)
                await repo.update(pid, {"claude_analysis": json.dumps(analysis, ensure_ascii=False)})
                analyzed += 1
                logger.info("n8n ANALYSIS [%d] %s -> verdict=%s",
                            pid, prospect.get("full_name", "?"), analysis.get("verdict"))
            except Exception:
                logger.error("n8n analysis error for %d:", pid, exc_info=True)
        await db.commit()

    return {"analyzed": analyzed, "total_pending": len(ids)}


# --- Batch: web research (CRM calls Claude internally) ---

@router.post("/web-research-batch")
async def web_research_batch(request: Request, limit: int = Body(5)):
    """Web research unresearched prospects using Claude (Sonnet)."""
    _step(request, "analyzing", "n8n: recherche web en cours...")

    web_svc = DeepAnalysisService()
    researched = 0

    async with get_db() as db:
        cur = await db.execute(
            "SELECT id FROM prospects "
            "WHERE experience_json IS NOT NULL AND experience_json != '' AND experience_json != '[]' "
            "AND (web_research_json IS NULL OR web_research_json = '') "
            "ORDER BY relevance_score DESC LIMIT ?",
            (limit,),
        )
        ids = [r[0] for r in await cur.fetchall()]

        from app.repositories.prospect_repo import ProspectRepository
        repo = ProspectRepository(db)

        for i, pid in enumerate(ids):
            _step(request, "analyzing", f"n8n: web research {i+1}/{len(ids)}...")
            prospect = await repo.find_by_id(pid)
            if not prospect:
                continue
            try:
                wr = await web_svc.web_research_prospect(prospect)
                await repo.update(pid, {"web_research_json": json.dumps(wr, ensure_ascii=False)})
                researched += 1
                logger.info("n8n WEB RESEARCH [%d] %s -> %s",
                            pid, prospect.get("full_name", "?"), wr.get("company_website", ""))
            except Exception:
                logger.error("n8n web research error for %d:", pid, exc_info=True)
        await db.commit()

    return {"researched": researched, "total_pending": len(ids)}


# --- Batch: strategy improvement (CRM calls Claude Opus internally) ---

@router.post("/strategy/generate")
async def generate_strategy(request: Request):
    """Generate strategy improvement proposal using Claude (Opus)."""
    _step(request, "proposing", "n8n: Claude Opus analyse et propose...")

    async with get_db() as db:
        proposal = await research.propose_program_improvement(db)

    if not proposal.get("proposed_program"):
        return {"proposed_program": "", "analysis": proposal.get("analysis", ""), "applied": False}

    # Auto-accept if configured
    from app.config import settings
    applied_version = None

    if settings.AUTO_ACCEPT_IMPROVEMENTS:
        async with get_db() as db:
            applied_version = await research.apply_program(db, proposal["proposed_program"], author="claude-auto-n8n")
            await db.execute(
                "UPDATE prospect_program SET trigger = 'n8n-auto', change_reason = ? WHERE version = ?",
                (f"Auto-accepted from n8n strategy generation", applied_version),
            )
            await db.commit()
        logger.info("n8n KARPATHY KEEP: program v%d accepted", applied_version)

    return {
        "proposed_program": proposal.get("proposed_program", ""),
        "analysis": (proposal.get("analysis") or "")[:2000],
        "applied": applied_version is not None,
        "applied_version": applied_version,
    }
